---
- name: Docker test
  hosts: all

  tasks:
    - name: ping
      ping:

- name: Create docker
  hosts: 127.0.0.1

  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: "docker<5"
      become: yes

    - docker_container:
        name: aaplication
        image: testapp
        ports:
          - 8000:8000
        command: python3 app.py